# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Myung-Hwan Jeon
title: Robotics Engineer
email: jmong1994@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: jekyllrb
github_username:  MyungHwanJeon
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: jeon____
linkedin_username: myung-hwan-jeon-544613219
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
orcid_username: 0000-0003-3611-0298
googlescholar_username: ivOqySYAAAAJ



# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/me.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Myung-Hwan Jeon.   
  
content:
  - title: Field of Interest
    layout: text
    content: | # this will include new lines to allow paragraphs
      Robot Vision, 6D Object Pose Estimation, Robot Manipulation, Simultaneous Localization and Mapping(SLAM), Spatial AI
            
  - title: Positions
    layout: list
    content:
    
      - layout: top-left
        title: SNU 
        sub_title: Post-Doctoral Research Fellow
        caption: Jan. 2023 - 
        link: http://rpm.snu.ac.kr/
        description: | # this will include new lines to allow paragraphs
          <br/> A post-doctoral research fellow in [RPM robotics Lab](https://rpm.snu.ac.kr) at [SNU](https://www.snu.ac.kr), advised by [Prof. Ayoung Kim](https://ayoungk.github.io/).  
    
      - layout: top-left
        title: SNU 
        sub_title: Graduate Student Teaching Assistant
        caption: Sep. 2022 - Dec. 2022   
        link: http://www.snu.ac.kr/
        description: | # this will include new lines to allow paragraphs
          <br/> I served as an teaching assistant in a lecture, AIME: Advanced Topics in Mechanical Engineering 4.        
    
      - layout: top-left
        title: KAIST
        sub_title: Graduate Student Teaching Assistant
        caption: Sep. 2019 - Dec. 2019   
        link: http://www.kaist.ac.kr/
        description: | # this will include new lines to allow paragraphs
          <br/> I served as an teaching assistant in a lecture, CE544: Mechanical Design of Civil Robot.    
    
      - layout: top-left
        title: CHIC
        sub_title: Researcher
        caption: Jan. 2017 - Jan. 2018   
        link: http://www.chic.re.kr/
        description: | # this will include new lines to allow paragraphs
          <br/> I conducted research into an interactive interface for VR/AR. Specifically, I developed an interface for manipulating complex articulated objects placed in virtual space.


  - title: Education
    layout: list
    content:
    
      - layout: top-left
        title: KAIST
        sub_title: Ph.D. in Robotic Program
        caption: Mar. 2020 - Feb. 2023       
        link: http://www.kaist.ac.kr/               
        description: | # this will include new lines to allow paragraphs
          <br/> I received a Ph.D. degree in robotic program in KAIST. I was a member of the IRAP lab (currently moved to the [RPM robotics Lab](https://rpm.snu.ac.kr), [SNU](https://www.snu.ac.kr)), and advised by [Prof. Ayoung Kim](https://ayoungk.github.io/).   

    
      - layout: top-left
        title: KAIST
        sub_title: M.S. in Robotic Program
        caption: Mar. 2018 - Feb. 2020       
        link: http://www.kaist.ac.kr/               
        description: | # this will include new lines to allow paragraphs
          <br/> I received a M.S. degree in robotic program in KAIST. I was a member of the IRAP lab (currently moved to the [RPM robotics Lab](https://rpm.snu.ac.kr), [SNU](https://www.snu.ac.kr)), and advised by [Prof. Ayoung Kim](https://ayoungk.github.io/).   
                
      - layout: top-left
        title: Kwangwoon University
        sub_title: B.S. in Division of Robotics
        caption: Mar. 2012 - Feb. 2017   
        link: http://www.kw.ac.kr/ 
        description: | # this will include new lines to allow paragraphs
          <br/> I received a B.S. degree in a division of Robotics at Kwangwoon university. Also, I conducted various robotics-related projects in "[BARAM](https://cafe.naver.com/roboticsbaram)", an academic club.
              
  - title: Projects
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left        
        title: PrimA6D
        caption: 2020
        link: https://www.youtube.com/watch?v=HbNmsmTLRmk
        link_text: Video
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/rpmsnu/PrimA6D
        description: | # this will include new lines to allow paragraphs        
        
          <div class="row clearfix">  
            <div class="col-xs-12 col-sm-4 col-md-3 no-print">
              <br/> 
              <a href="https://www.youtube.com/watch?v=HbNmsmTLRmk"><img src="images/prima6d.png" width="100%" alt="IMAGE ALT TEXT"></a>      
            </div>
            <div class="col-sm-8 col-md-9 col-print-12">                            
              <p> We proposed a novel 6D object pose estimation method introducing a rotational primitive.</p>
              <ul>
                <li><U><b>Myung-Hwan Jeon</b></U> and Ayoung Kim, <a href="https://arxiv.org/abs/2006.07789">"PrimA6D: Rotational Primitive Reconstruction for Enhanced and Robust 6D Pose Estimation"</a>, in IEEE Robotics and Automation Letters, 2020. </li>
              </ul>     
            </div>
          </div>    
          
      - layout: top-left        
        title: PrimA6D++
        caption: 2022
        link: https://www.youtube.com/watch?v=akbI61jUJgY
        link_text: Video
        additional_links:
          - title: Github page for project
            icon: fab fa-github
            url: https://github.com/rpmsnu/PrimA6D
        description: | # this will include new lines to allow paragraphs        
        
          <div class="row clearfix">  
            <div class="col-xs-12 col-sm-4 col-md-3 no-print">                     
              <a href="https://www.youtube.com/watch?v=HbNmsmTLRmk"><img src="images/prima6dpp.png" width="100%" alt="IMAGE ALT TEXT"></a>      
            </div>
            <div class="col-sm-8 col-md-9 col-print-12">                            
              <p> We presented an ambiguity-aware 6D object pose estimation network, PrimA6D++, as a generic uncertainty prediction method.</p>
              <ul>
                <li><U><b>Myung-Hwan Jeon</b></U>, Jeongyun Kim and Ayoung Kim, <a href="https://rpm.snu.ac.kr/publications/mjeon-2022-ral.pdf">"Ambiguity-Aware Multi-Object Pose Optimization for Visually-Assisted Robot Manipulation",</a>, in IEEE Robotics and Automation Letters, 2022. </li>
              </ul>    
            </div>
          </div>        
          
      - layout: top-left        
        title: STheReO Dataset
        caption: 2022
        link: https://www.youtube.com/watch?v=U81_vpHymAA
        link_text: Video
        additional_links:
          - title: Project page
            icon: fab fa-dribbble-square
            url: https://sites.google.com/view/rpmsthereo/
        description: | # this will include new lines to allow paragraphs        
        
          <div class="row clearfix">  
            <div class="col-xs-12 col-sm-4 col-md-3 no-print">
              <br/> 
              <a href="https://www.youtube.com/watch?v=U81_vpHymAA"><img src="images/sthereo.png" width="100%" alt="IMAGE ALT TEXT"></a>      
            </div>
            <div class="col-sm-8 col-md-9 col-print-12">                            
              <p> We presented an Stereo Thermal Dataset for Research in Odometry and Mapping.</p>
              <ul>
                <li>Seungsang Yun, Minwoo Jung, Jeongyun Kim, Sangwoo Jung, Younghun Cho, <U><b>Myung-Hwan Jeon</b></U>, Giseop Kim, and Ayoung Kim, <a href="https://rpm.snu.ac.kr/publications/ssyun-2022-iros.pdf">"STheReO: Stereo Thermal Dataset for Research in Odometry and Mapping"</a>, Proceedings of the IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS), 2022</li>
              </ul>   
            </div>
          </div>                                                   
              
  - title: Projects in <a href="https://cafe.naver.com/roboticsbaram">BARAM</a>, a academic club
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left        
        title: Self-Balancing Bike
        caption: 2013
        link: https://youtu.be/xUFVXe3pzGw?t=79
        link_text: Video
        description: | # this will include new lines to allow paragraphs        
        
          <div class="row clearfix">  
            <div class="col-xs-12 col-sm-4 col-md-3 no-print">
              <a href="https://youtu.be/xUFVXe3pzGw?t=79"><img src="images/bike.png" width="100%" alt="IMAGE ALT TEXT"></a>      
            </div>
            <div class="col-sm-8 col-md-9 col-print-12">                            
              <p> <br/> I developed a self-balancing bike exploiting the concept of a reaction wheel pendulum.</p>
            </div>
          </div>
          
      - layout: top-left        
        title: Intelligent Model Car
        caption: 2013
        link: https://youtu.be/aAwuEpfIuqc
        link_text: Video
        description: | # this will include new lines to allow paragraphs        
        
          <div class="row clearfix">  
            <div class="col-xs-12 col-sm-4 col-md-3 no-print">
              <a href="https://youtu.be/aAwuEpfIuqc"><img src="images/intel_car.png" width="100%" alt="IMAGE ALT TEXT"></a>      
            </div>
            <div class="col-sm-8 col-md-9 col-print-12">                            
              <p> <br/> We developed an intelligent model car based on the line-tracer.</p>
              <ul>
                <li>"<b>BMW Special Prize</b>", 2013 Hanyang Univ. Intelligent Model Car Racing.</li>                
              </ul>
            </div>
          </div>          
          
      - layout: top-left        
        title: Delta Robot Application
        caption: 2013
        link: https://www.youtube.com/watch?v=zkZKcts7cQ4
        link_text: Video
        description: | # this will include new lines to allow paragraphs        
        
          <div class="row clearfix">  
            <div class="col-xs-12 col-sm-4 col-md-3 no-print">
              <br/>
              <br/>
              <a href="https://www.youtube.com/watch?v=zkZKcts7cQ4"><img src="images/delta.png" width="100%" alt="IMAGE ALT TEXT"></a>      
            </div>
            <div class="col-sm-8 col-md-9 col-print-12">                            
              <p> <br/> We developed a delta robot of parallel robots for object detection with robot vision on the conveyor belt. <br/> </p>              
              <ul>
                <li>"<b>Chairman's Award</b>", Texas Instrument (TI) Innovation Challenge: Korean MCU design context 2013.</li>                
              </ul>              
            </div>
          </div>  
          
      - layout: top-left        
        title: Human-Robot Interaction System
        caption: 2015
        link: https://www.youtube.com/watch?v=IBtf0JAw3jA
        link_text: Video
        description: | # this will include new lines to allow paragraphs        
        
          <div class="row clearfix">  
            <div class="col-xs-12 col-sm-4 col-md-3 no-print">
              <br/>
              <br/>              
              <a href="https://www.youtube.com/watch?v=IBtf0JAw3jA"><img src="images/helper.png" width="100%" alt="IMAGE ALT TEXT"></a>      
            </div>
            <div class="col-sm-8 col-md-9 col-print-12">                            
              <p> <br/> We developed a Human-Robot Interaction (HRI) system for a robot manipulator called "helper". <br/> </p>              
              <ul>
                <li>"<b>Top Award</b>", 17th Korea Intelligent Robot Contest.</li>     
                <li>"<b>Top Award</b>", 2015 Nowon-gu, Seoul Capstone Design Contest.</li>   
              </ul>              
            </div>
          </div>          
          
      - layout: top-left        
        title: Dotuator & Dotkey
        caption: 2016
        link: https://www.youtube.com/watch?v=tfgsq2MSX-A
        link_text: Video
        description: | # this will include new lines to allow paragraphs        
        
          <div class="row clearfix">  
            <div class="col-xs-12 col-sm-4 col-md-3 no-print">
              <br/>
              <br/>
              <br/>
              <a href="https://www.youtube.com/watch?v=tfgsq2MSX-A"><img src="images/dot.png" width="100%" alt="IMAGE ALT TEXT"></a>      
            </div>
            <div class="col-sm-8 col-md-9 col-print-12">                            
              <p> <br/> We developed a mobile braille device and a braille keyboard for smartphone. We tried to improve the life quality for the visually impaired. <br/> </p>              
              <ul>
                <li>"<b>Encouragement Prize</b>", 18th Korea Intelligent Robot Contest.</li>   
                <li>"<b>Special Prize</b>", 18th Korea Intelligent Robot Contest.</li>
                <li>"<b>Excellence Prize</b>", 12th Kwangwoon IT Exhibition.</li>
                <li>"<b>Excellence Prize</b>", 5th Kwangwoon software programming contest.</li>
                <li>"<b>Top Award</b>", 2017 Nowon-gu, Seoul Capstone Design Contest.</li>
              </ul>              
            </div>
          </div>                    
         
  
          
  - title: Publications
    layout: text
    content: |
    
      - **<U>Myung-Hwan Jeon</U>** and Ayoung Kim, “[Measuring Prediction Reliability on 6D Object Pose Estimation](https://youtu.be/qSHd3oweD34)”, in Late-Breaking Results Poster on IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS), 2022.
     
      - **<U>Myung-Hwan Jeon</U>**, Jeongyun Kim, Jee-Hwan Ryu, and Ayoung Kim, "[Ambiguity-Aware Multi-Object Pose Optimization for Visually-Assisted Robot Manipulation](https://rpm.snu.ac.kr/publications/mjeon-2022-ral.pdf)", in IEEE Robotics and Automation Letters (RA-L), 2022.
     
      - Eon-ho Lee, Byungjae Park,  **<U>Myung-Hwan Jeon</U>**, Hyesu Jang, Ayoung Kim and Sejin Lee, "[Data augmentation using image translation for underwater sonar image segmentation](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0272602)", in PLoS ONE 17(8), 2022.
     
      - Seungsang Yun, Minwoo Jung, Jeongyun Kim, Sangwoo Jung, Younghun Cho, **<U>Myung-Hwan Jeon</U>**, Giseop Kim, and Ayoung Kim, "[STheReO: Stereo Thermal Dataset for Research in Odometry and Mapping](https://rpm.snu.ac.kr/publications/ssyun-2022-iros.pdf)", in IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS), 2022

      - Jeongyun Kim, **<U>Myung-Hwan Jeon</U>**, and Ayoung Kim, "[Enhancing Single Thermal Image Depth Estimation via Multi-Channel Remapping for Thermal Images](http://jkros.org/xml/33768/33768.pdf)", in Journal of Korea Robotics Society (KROS), 2022.

      - Joowan Kim, **<U>Myung-Hwan Jeon</U>**, Younggun Cho, Ayoung Kim, "[Dark Synthetic Vision: Lightweight Active Vision to Navigate in the Dark](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9246220)", in IEEE Robotics and Automation Letters (RA-L), 2021.
      
      - **<U>Myung-Hwan Jeon</U>** and Ayoung Kim, "[PrimA6D: Rotational Primitive Reconstruction for Enhanced and Robust 6D Pose Estimation](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9123683)", in IEEE Robotics and Automation Letters (RA-L), 2020.
      
      - Eon-Ho Lee, **<U>Myung-Hwan Jeon</U>**, Hyesu Jang, Byungjae Park, Ayoung Kim, and Sejin Lee, "[Study on the Training Effectiveness of Deep Learning with Synthesized Underwater Sonar Image Using Pix2Pix and FCN](https://ieeexplore.ieee.org/abstract/document/9267923)", in IEEE/OES Autonomous Underwater Vehicles Symposium (AUV), 2020.

      - Jun-Sik Kim, **<U>Myung-Hwan Jeon</U>**, and Jung-Min Park, "[Multi-Hand Direct Manipulation of Complex Constrained Virtual Objects](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8968088)", in IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS), 2019.      

      - **<U>Myung-Hwan Jeon</U>**, Yeongjun Lee, Young-Sik Shin, Hyesu Jang, Taekyeong Yeu, and Ayoung Kim, “[Synthesizing Image and Automated Annotation Tool for CNN based Under Water Object Detection](https://koreascience.kr/article/JAKO201916936725841.pdf)”, in Journal of Korea Robotics Society (KROS), 2019.

      - **<U>Myung-Hwan Jeon</U>**, Yeongjun Lee, Young-Sik Shin, Hyesu Jang, and Ayoung Kim, "[Underwater Object Detection and Pose Estimation using Deep Learning](https://www.sciencedirect.com/science/article/pii/S2405896319321718)", in 12th IFAC Conference on Control Applications in Marine Systems, Robotics, and Vehicles (CAMS), 2019.

      - **<U>Myung-Hwan Jeon</U>**, Yeongjun Lee, Young-Sik Shin, Hyesu Jang, and Ayoung Kim, "[Deep Learning Based Underwater Object Detection and Pose Estimation](http://irosworkshop.marinerobotics.eu/wp-content/uploads/2018/10/Fr-WS19-08.pdf)", in Workshop on IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS), 2018.           

  - title: Services
    layout: text
    content: |
     
            <ul>
              <li><b>Reviewer</b></li>
              <ul>
                <li>IEEE International Conference on Ubiquitous Robots (UR, 2020)</li>   
                <li>IEEE International Conference on Robotics and Automation (ICRA, 2021)</li>
                <li>IEEE International Conference on Robotics and Automation (ICRA, 2022)</li>
                <li>IEEE International Conference on Intelligent Robots and Systems (IROS, 2022)</li>
                <li>IEEE Robotics and Automation Letters (RA-L, 2022)</li>
                <li>IEEE International Conference on Robotics and Automation (ICRA, 2023) </li>
              </ul>  
            </ul>

  - title: Acknowledgement
    layout: text
    content: |
    
      MIT License, Copyright (c) 2018 James Grant.
      <br/>
      This page is based on the [modern-resyme-theme](https://github.com/sproogen/modern-resume-theme).

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
