# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Myung-Hwan Jeon
title: Ph.D. Candidate of Robotics Program
email: myunghwan.jeon@kaist.ac.kr
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: jekyllrb
github_username:  MyungHwanJeon
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: jeon____
linkedin_username: myung-hwan-jeon-544613219
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
orcid_username: 0000-0003-3611-0298
googlescholar_username: ivOqySYAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/me.JPG
about_content: | # this will include new lines to allow paragraphs
  I am a Ph.D. candidate of [Robotic Progrom](https://rp.kaist.ac.kr) in [KAIST](https://www.kaist.ac.kr). Due to personal reasons, I am currently a member of the [RPM robotics Lab](https://rpm.snu.ac.kr), [SNU](https://www.snu.ac.kr), advised by [Prof. Ayoung Kim](https://ayoungk.github.io/).
  
content:
  - title: Field of Interest
    layout: text
    content: | # this will include new lines to allow paragraphs
      Robot Vision, 6D Object Pose Estimation, Robot Manipulation, Simultaneous Localization and Mapping(SLAM), Spatial AI
            
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
  - title: Positions
    layout: list
    content:
    
      - layout: top-left
        title: SNU 
        sub_title: Graduate Student Teaching Assistant
        caption: Sep. 2022 - Dec. 2022   
        link: http://www.snu.ac.kr/
        quote: >
          Seoul National University(SNU) was estblished in 1895 and is located in Seoul, Korea.
        description: | # this will include new lines to allow paragraphs
          I executed an assistant in a lecture, AIME: Advanced Topics in Mechanical Engineering 4.        
    
      - layout: top-left
        title: KIAST 
        sub_title: Graduate Student Teaching Assistant
        caption: Sep. 2019 - Dec. 2019   
        link: http://www.kaist.ac.kr/
        quote: >
          Korea Advanced Institute of Science and Technology(KAIST) was estblished in 1971 and is located in Daejeon, Korea.
        description: | # this will include new lines to allow paragraphs
          I executed an assistant in a lecture, CE544: Mechanical Design of Civil Robot.    
    
      - layout: top-left
        title: CHIC
        sub_title: Researcher
        caption: Jan. 2017 - Jan. 2018   
        link: http://www.chic.re.kr/
        quote: >
          A Center of Human-centered Interaction for Coexistence(CHIC) is established in 2010 and located in Seoul, Korea.
        description: | # this will include new lines to allow paragraphs
          I conducted research into an interactive interface for VR/AR. Specifically, I developed an interface for manipulating complex articulated objects placed in virtual space.


  - title: Education
    layout: list
    content:
    
      # - layout: top-left
      #  title: KAIST
      #  sub_title: Ph.D. in Robotic Program
      #  caption: Mar. 2020 - Feb. 2023       
      #  quote: >
      #    Korea Advanced Institute of Science and Technology(KAIST) was estblished in 1971 and is located in Daejeon, Korea.                    
      #  description: | # this will include new lines to allow paragraphs
      #    Description of qualification        
    
      - layout: top-left
        title: KAIST
        sub_title: M.S. in Robotic Program
        caption: Mar. 2018 - Feb. 2020       
        quote: >
          Korea Advanced Institute of Science and Technology(KAIST) was estblished in 1971 and is located in Daejeon, Korea.                    
        description: | # this will include new lines to allow paragraphs
          I received a M.S. degree in robotic program in KAIST. I was a member of the IRAP lab (currently moved to the [RPM robotics Lab](https://rpm.snu.ac.kr), [SNU](https://www.snu.ac.kr)), and advised by [Prof. Ayoung Kim](https://ayoungk.github.io/).   
                
      - layout: top-left
        title: Kwangwoon University
        sub_title: B.S. in Division of Robotics
        caption: Mar. 2012 - Feb. 2017        
        quote: >
          Kwangwoon university was estblished in 1962 and is located in Seoul, Korea.    
        description: | # this will include new lines to allow paragraphs
          I received a B.S. degree in a division of Robotics at Kwangwoon university. Also, I conducted various robotics-related projects in "[BARAM](https://cafe.naver.com/roboticsbaram)", an academic club.
                 
          
  - title: Publications
    layout: list
    content:
    
      - layout: top-left
        title: 1 
        description: | # this will include new lines to allow paragraphs
          bbbbbbbbbbb
          
      - layout: top-left
        title: 2 
        description: | # this will include new lines to allow paragraphs
          bbbbbbbbbbb

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
