# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Myung-Hwan Jeon
title: Ph.D. Candidate of Robotics Program
email: myunghwan.jeon@kaist.ac.kr
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: jekyllrb
github_username:  MyungHwanJeon
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: jeon____
linkedin_username: myung-hwan-jeon-544613219
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
orcid_username: 0000-0003-3611-0298
googlescholar_username: ivOqySYAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/me.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Myung-Hwan Jeon and I'm a Ph.D. candidate of [Robotic Progrom](https://rp.kaist.ac.kr) in [KAIST](https://www.kaist.ac.kr). Due to personal reasons, I am currently a member of the [RPM robotics Lab](https://rpm.snu.ac.kr), [SNU](https://www.snu.ac.kr), advised by [Prof. Ayoung Kim](https://ayoungk.github.io/).
  
content:
  - title: Field of Interest
    layout: text
    content: | # this will include new lines to allow paragraphs
      Robot Vision, 6D Object Pose Estimation, Robot Manipulation, Simultaneous Localization and Mapping(SLAM), Spatial AI
            
  - title: Positions
    layout: list
    content:
    
      - layout: top-left
        title: SNU 
        sub_title: Graduate Student Teaching Assistant
        caption: Sep. 2022 - Dec. 2022   
        link: http://www.snu.ac.kr/
        quote: >
         
        #  Seoul National University(SNU) was estblished in 1895 and is located in Seoul, Korea.
        description: | # this will include new lines to allow paragraphs
          I executed an assistant in a lecture, AIME: Advanced Topics in Mechanical Engineering 4.        
    
      - layout: top-left
        title: KIAST 
        sub_title: Graduate Student Teaching Assistant
        caption: Sep. 2019 - Dec. 2019   
        link: http://www.kaist.ac.kr/
        quote: >
        
        #  Korea Advanced Institute of Science and Technology(KAIST) was estblished in 1971 and is located in Daejeon, Korea.
        description: | # this will include new lines to allow paragraphs
          I executed an assistant in a lecture, CE544: Mechanical Design of Civil Robot.    
    
      - layout: top-left
        title: CHIC
        sub_title: Researcher
        caption: Jan. 2017 - Jan. 2018   
        link: http://www.chic.re.kr/
        quote: >
        
        #  A Center of Human-centered Interaction for Coexistence(CHIC) is established in 2010 and located in Seoul, Korea.
        description: | # this will include new lines to allow paragraphs
          I conducted research into an interactive interface for VR/AR. Specifically, I developed an interface for manipulating complex articulated objects placed in virtual space.


  - title: Education
    layout: list
    content:
    
      # - layout: top-left
      #  title: KAIST
      #  sub_title: Ph.D. in Robotic Program
      #  caption: Mar. 2020 - Feb. 2023       
      #  quote: >
      #    Korea Advanced Institute of Science and Technology(KAIST) was estblished in 1971 and is located in Daejeon, Korea.                    
      #  description: | # this will include new lines to allow paragraphs
      #    Description of qualification        
    
      - layout: top-left
        title: KAIST
        sub_title: M.S. in Robotic Program
        caption: Mar. 2018 - Feb. 2020       
        link: http://www.kaist.ac.kr/
        quote: >
        
        #  Korea Advanced Institute of Science and Technology(KAIST) was estblished in 1971 and is located in Daejeon, Korea.                    
        description: | # this will include new lines to allow paragraphs
          I received a M.S. degree in robotic program in KAIST. I was a member of the IRAP lab (currently moved to the [RPM robotics Lab](https://rpm.snu.ac.kr), [SNU](https://www.snu.ac.kr)), and advised by [Prof. Ayoung Kim](https://ayoungk.github.io/).   
                
      - layout: top-left
        title: Kwangwoon University
        sub_title: B.S. in Division of Robotics
        caption: Mar. 2012 - Feb. 2017   
        link: http://www.kw.ac.kr/
        quote: >
        
        #  Kwangwoon university was estblished in 1962 and is located in Seoul, Korea.    
        description: | # this will include new lines to allow paragraphs
          I received a B.S. degree in a division of Robotics at Kwangwoon university. Also, I conducted various robotics-related projects in "[BARAM](https://cafe.naver.com/roboticsbaram)", an academic club.
              
              
  - title: Projects in BARAM, a academic club
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left        
        title: Self-Balancing Bike
        caption: 2013
        link: https://youtu.be/xUFVXe3pzGw?t=79
        link_text: Video
        #quote: >
        #  
        image: images/me.JPG
        comment: I developed a self-balancing bike exploiting the concept of a reaction wheel pendulum. From hardware design to firmware design, I did everything myself.
        description: | # this will include new lines to allow paragraphs        
          <div class="row clearfix">  
            <div class="col-xs-12 col-sm-4 col-md-3 no-print">
              <span class="profile-img" style="background-image: url({{image | relative_url }})"></span>
            </div>

            <div class="col-sm-8 col-md-9 col-print-12">
              {{ comment| strip | markdownify }}
            </div>
          </div>
         
                                               
          
  - title: Publications
    layout: text
    content: |
     
      - Eon-ho Lee, Byungjae Park,  **<U>Myung-Hwan Jeon</U>**, Hyesu Jang, Ayoung Kim and Sejin Lee, "[Data augmentation using image translation for underwater sonar image segmentation](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0272602)", in PLoS ONE 17(8): e0272602. https://doi.org/10.1371/journal.pone.0272602
     
      - Seungsang Yun, Minwoo Jung, Jeongyun Kim, Sangwoo Jung, Younghun Cho, **<U>Myung-Hwan Jeon</U>**, Giseop Kim, and Ayoung Kim, "STheReO: Stereo Thermal Dataset for Research in Odometry and Mapping", Proceedings of the IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS), 2022

      - Jeongyun Kim, **<U>Myung-Hwan Jeon</U>**, and Ayoung Kim, "[Enhancing Single Thermal Image Depth Estimation via Multi-Channel Remapping for Thermal Images](http://jkros.org/xml/33768/33768.pdf)", in Journal of Korea Robotics Society, vol. 17, no. 3. The Korea Robotics Society, pp. 314–321, 2022.

      - Joowan Kim, **<U>Myung-Hwan Jeon</U>**, Younggun Cho, Ayoung Kim, "[Dark Synthetic Vision: Lightweight Active Vision to Navigate in the Dark](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9246220)", in IEEE Robotics and Automation Letters, vol. 6, no. 1, pp. 143-150, Jan. 2021, doi: 10.1109/LRA.2020.3035137.
      
      - **<U>Myung-Hwan Jeon</U>** and Ayoung Kim, "[PrimA6D: Rotational Primitive Reconstruction for Enhanced and Robust 6D Pose Estimation](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9123683)", in IEEE Robotics and Automation Letters, vol. 5, no. 3, pp. 4955-4962, 2020.
      
      - Eon-Ho Lee, **<U>Myung-Hwan Jeon</U>**, Hyesu Jang, Byungjae Park, Ayoung Kim, and Sejin Lee, "[Study on the Training Effectiveness of Deep Learning with Synthesized Underwater Sonar Image Using Pix2Pix and FCN](https://ieeexplore.ieee.org/abstract/document/9267923)", in 2020 IEEE/OES Autonomous Underwater Vehicles Symposium (AUV), 2020.

      - Jun-Sik Kim, **<U>Myung-Hwan Jeon</U>**, and Jung-Min Park, "[Multi-Hand Direct Manipulation of Complex Constrained Virtual Objects](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8968088)", in 2019 IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS), 2019, pp. 3235-3240, doi: 10.1109/IROS40897.2019.8968088.      

      - **<U>Myung-Hwan Jeon</U>**, Yeongjun Lee, Young-Sik Shin, Hyesu Jang, Taekyeong Yeu, and Ayoung Kim, “[Synthesizing Image and Automated Annotation Tool for CNN based Under Water Object Detection](https://koreascience.kr/article/JAKO201916936725841.pdf)”, in Journal of Korea Robotics Society, vol. 14, no. 2. The Korea Robotics Society, pp. 139–149, 2019.

      - **<U>Myung-Hwan Jeon</U>**, Yeongjun Lee, Young-Sik Shin, Hyesu Jang, and Ayoung Kim, "[Underwater Object Detection and Pose Estimation using Deep Learning](https://www.sciencedirect.com/science/article/pii/S2405896319321718)", in 12th IFAC Conference on Control Applications in Marine Systems, Robotics, and Vehicles , 2019.

      - **<U>Myung-Hwan Jeon</U>**, Yeongjun Lee, Young-Sik Shin, Hyesu Jang, and Ayoung Kim, "[Deep Learning Based Underwater Object Detection and Pose Estimation](http://irosworkshop.marinerobotics.eu/wp-content/uploads/2018/10/Fr-WS19-08.pdf)", in workshop on IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS), 2018.

  - title: Acknowledgement
    layout: text
    content: |
    
      MIT License, Copyright (c) 2018 James Grant

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
